### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by nomi-san** [Warfley/AU3IDE#1]
As the title says.
-----
I found a download link [https://automatestudio.org/Installer.zip](https://automatestudio.org/Installer.zip), but the server died.

**Comment by Warfley** [comment]
Yeah, I don't own that domain anymore. This project is build with Lazarus 1.6.4. I just added a simple Readme.

If you just want to try it out, I just uploaded a release package to github: https://github.com/Warfley/AU3IDE/releases
or, if you want to install it (which associates the file ending and registers the program into the start menu), the new url is https://kehrein.eu/automatestudio/Installer.zip
